In [1]:
import dlib
import cv2 
path = 'chinh.jpg'
#path = '3.jpg'
img2= cv2.imread(path, cv2.IMREAD_COLOR)
img = img2.copy()
#location = detector(img,2)

In [2]:
detector=dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor('dlib_models/shape_predictor_68_face_landmarks.dat')

In [1]:
def is_image(path):
    print(path)
    try:
        extensions = path[-4:]
        image_extensions = ["png", "PNG", "jpg", "JPG"]

        if extensions[1:] in image_extensions:
            return True 
        else:
            print("Please input image file. png / jpg")
            return False 
    except: 
        return False 

In [2]:
is_image('asd/1.jpg')

asd/1.jpg


True

In [10]:
shape 

In [11]:
cv2.imshow('a',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
from easydict import EasyDict
from utils.aux_functions import *
args = EasyDict()
args.code = None
args.mask_type = 'cloth'
args.predictor = predictor
args.detector = detector
args.verbose = False
args.pattern = False
args.color = False

In [13]:
face_locations = args.detector(img, 1)
face_location = face_locations[0]
shape = args.predictor(img, face_location)
shape = face_utils.shape_to_np(shape)
face_landmarks = shape_to_landmarks(shape)
face_location = rect_to_bb(face_location)
six_points,angle = get_six_points(face_landmarks, img)

In [5]:
face_landmark = face_landmarks
left_eye = face_landmark["left_eye"]   # return a center point of left eye
right_eye = face_landmark["right_eye"]
left_eye_mid = np.mean(np.array(left_eye), axis=0)
right_eye_mid = np.mean(np.array(right_eye), axis=0)
eye_line_mid = (left_eye_mid + right_eye_mid) / 2

In [15]:
face_landmarks

{'left_eyebrow': [(197, 395), (218, 376), (246, 373), (272, 381), (297, 394)],
 'right_eyebrow': [(336, 395), (362, 384), (389, 380), (416, 385), (436, 402)],
 'nose_bridge': [(317, 431), (317, 453), (317, 474), (316, 497)],
 'nose_tip': [(283, 531), (298, 534), (314, 537), (330, 535), (347, 533)],
 'left_eye': [(223, 437),
  (237, 428),
  (256, 429),
  (275, 440),
  (255, 444),
  (237, 444)],
 'right_eye': [(357, 442),
  (375, 432),
  (393, 433),
  (409, 442),
  (393, 449),
  (375, 448)],
 'top_lip': [(253, 598),
  (274, 580),
  (298, 569),
  (314, 575),
  (331, 570),
  (353, 582),
  (374, 600),
  (263, 598),
  (298, 591),
  (314, 592),
  (331, 592),
  (364, 600)],
 'bottom_lip': [(374, 600),
  (352, 617),
  (331, 624),
  (313, 625),
  (294, 623),
  (273, 615),
  (253, 598),
  (364, 600),
  (330, 599),
  (313, 600),
  (296, 598),
  (263, 598)],
 'chin': [(165, 446),
  (164, 485),
  (165, 526),
  (171, 565),
  (182, 604),
  (201, 638),
  (230, 665),
  (265, 686),
  (308, 693),
  (349, 

In [24]:
img=img2.copy()
cv2.namedWindow('a',cv2.WINDOW_NORMAL)
for i in face_landmarks['top_lip']:
    img = cv2.circle(img, (int(i[0]),int(i[1])), radius=4, color=(0, 0, 255), thickness=-1)
    cv2.imshow('a',img)
    k = cv2.waitKey(0)
    if k==ord('q'):
        break
cv2.destroyAllWindows()
    

(364, 600)

In [20]:
cv2.namedWindow('a',cv2.WINDOW_NORMAL)
cv2.imshow('a',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [55]:
eye_line, perp_line, left_point, right_point, mid_point=get_line(face_landmarks,img,type='perp_line')

In [42]:
i =mid_point

In [99]:
face_landmark["left_eye"]

NameError: name 'face_landmark' is not defined

In [5]:
cfg = read_cfg(config_filename="masks/masks.cfg", mask_type='cloth', verbose=False)

In [6]:
mask_line = np.float32(
    [cfg.mask_a, cfg.mask_b, cfg.mask_c, cfg.mask_f, cfg.mask_e, cfg.mask_d]
)

In [9]:
mask_line

array([[122.,  90.],
       [405.,   7.],
       [686.,  79.],
       [653., 311.],
       [406., 509.],
       [165., 323.]], dtype=float32)

In [10]:
M, mask = cv2.findHomography(mask_line, six_points)

In [15]:
from skimage import transform as trans
tform = trans.SimilarityTransform() 
tform.estimate(mask_line,six_points)
M = tform.params#[0:2,:]

In [11]:
M

array([[5.72749687e-01, 1.75577171e-01, 8.55889554e+01],
       [2.96772522e-02, 9.17940243e-01, 4.45921223e+02],
       [1.50682085e-06, 6.44700250e-04, 1.00000000e+00]])

In [16]:
tform.params

array([[ 4.95509010e-01, -2.43965473e-02,  1.17043634e+02],
       [ 2.43965473e-02,  4.95509010e-01,  4.50597637e+02],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [76]:
mask_img = cv2.imread(cfg.template)

In [93]:
out_img,mask = mask_face(img, face_location, six_points, angle, args, type="cloth")

In [95]:
cv2.namedWindow('a',cv2.WINDOW_NORMAL)
cv2.imshow('a',out_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [95]:
np.unique(mask)

array([  0,   1,   2,   3,   5,   7,   8,   9,  13,  16,  17,  19,  21,
        23,  28,  31,  32,  33,  35,  39,  40,  42,  44,  47,  49,  58,
        59,  61,  64,  70,  72,  82,  85,  94, 102, 112, 113, 119, 121,
       123, 126, 127, 129, 130, 131, 132, 133, 136, 154, 155, 162, 165,
       168, 172, 174, 179, 190, 192, 198, 212, 218, 220, 221, 225, 230,
       233, 235, 242, 243, 244, 246, 247, 249, 250, 251, 252, 253, 254,
       255], dtype=uint8)

In [113]:
mid_point

59.0

In [110]:
img2 = img.copy()
for i in face_landmarks['nose_bridge']:
    img2 = cv2.circle(img2, (int(i[0]), int(i[1])), radius=1,color=(0,0,255),thickness=-1)


In [116]:
a=get_line(face_landmark,img,type='nose_mid',debug=True)
nose_tip
bottom_lip
perp_line
nose_long

NameError: name 'nose_tip' is not defined

In [120]:
a=get_line(face_landmark,img,type='nose_long',debug=True)

In [5]:
six_points

array([[164.37985, 500.574  ],
       [316.5    , 464.     ],
       [468.61133, 509.48923],
       [426.4252 , 628.253  ],
       [310.01236, 692.92554],
       [191.70949, 621.3749 ]], dtype=float32)

In [19]:
out_img,mask = mask_face(img, face_location, six_points, angle, args, type="cloth")

In [18]:
six_points[0][1] = 500
six_points[1][1] = 464+180#80
six_points[2][1] = 509+0#60
six_points[3][1] = 628+0#80
six_points[4][1] = 692+0#80
six_points[5][1] = 621.92554

In [8]:
six_points

array([[164.37985, 500.574  ],
       [316.5    , 464.     ],
       [468.61133, 509.48923],
       [426.4252 , 628.253  ],
       [310.01236, 692.92554],
       [191.70949, 621.3749 ]], dtype=float32)

In [13]:
import cv2 
import numpy as np
img = cv2.imread('chinh.jpg', cv2.IMREAD_COLOR)
mask = cv2.imread('masks/templates/cloth.png', cv2.IMREAD_COLOR)

In [9]:
mask_inv = cv2.bitwise_not(mask)

In [15]:
mask_inv.shape

(533, 800, 3)

In [11]:
cv2.namedWindow('a', cv2.WINDOW_NORMAL)
cv2.imshow('a',mask_inv)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
mask.shape

(533, 800, 3)

In [14]:
img.shape

(960, 719, 3)